version: 1.0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:222866594907:task-definition/flask-bootstrap-staging:48"
        LoadBalancerInfo:
          ContainerName: "flask-bootstrap-staging-service"
          ContainerPort: 8000
        PlatformVersion: "LATEST"
