# Creates image called flask_bootstrap
# Runs dockerfile and maps uwsgi 8000 port to localhost 8080
# You can see app running at http://localhost:8080/
version: "3"

services:
  flask-bootstrap:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_bootstrap
    ports:
      - "8080:8000"
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:11
    # Ensure that data is persisted beyond the life of the container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env-postgres

volumes:
  postgres_data:
