version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Python Version
          command: |
            python --version
      - run:
          name: Install Python Dependencies
          command: |
            pip install --upgrade pip
            pip install pipenv
            pipenv install --dev --system
      - run:
          name: Run Linter
          command: |
            flake8 app
            flake8 tests
      - run:
          name: Run Pytest
          command: |
            pytest ./tests --junitxml=./shippable/testresults/flask_bootstrap.xml --cov=app --cov-report xml:./shippable/codecoverage/coverage.xml
      - store_test_results:
          path: ~/pytest
