version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Python Version
          command: |
            python --version
      - run:
          name: Install Python Dependencies
          command: |
            pip install --upgrade pip
            pip install pipenv
            pipenv install --dev
            pipenv shell
      - run:
          name: Run Linter
          command: |
            flake8 app
            flake8 tests
