version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Python Version
          command: |
            python --version
      - run:
          name: Install Python Dependencies
          command: |
            pip install --upgrade pip
            pip install pipenv
            pipenv install --dev --system
      - run:
          name: Run Linter
          command: |
            flake8 app
            flake8 tests
      - run:
          name: Run Pytest
          command: |
            pytest ./tests --junitxml=./cicleci/testresults/flask_bootstrap.xml --cov=app --cov-report html:./coverage/flask-bootstrap
      - store_artifacts:
          path: ./coverage/flask-bootstrap
      - store_test_results:
          path: ./cicleci

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Deploy image
          command: |
            echo TODO

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
            - build
      - deploy:
          requires:
            - hold